### ISSUE TITLE
Import the KP_find in python

### ISSUE THREAD

**Issue by patrickpca** [Asratum/KP_find#14]
Hi.
I'm new to Github and python.
How do I import the library into python?
a setup.py file is usually available to install the library.

Do I need to have qgis installed to run the functions?

thanks.

**Comment by patrickpca** [comment]
Starting from a data in excel with the coordinates.
How would I perform the KP one in a kilometer?

**Comment by Asratum** [comment]
Hi Patrick,

The plugin in its current form works only with QGIS. There are libraries in there that could be used to do it through python directly, but this is beyond the scope here.
If you have coordinates in excel, I would recommend to export them as a csv, import the points in QGIS and generate a line from these points. After this, you could use the plugin to find the KPs along that generated line.
Just search online a bit for some tutorials, this one might come in handy:
https://www.sigterritoires.fr/index.php/en/points-to-line-with-qgis/

**Comment by patrickpca** [comment]
Hi Asratum, 
I'm very happy with your answer.
Me and one more friend started this routine to perform KP.
When finished I will send the link on Github so that if it is useful for you and possible corrections as well.

**Comment by patrickpca** [comment]
My intention was to generate a routine that would pull these coordinates (lat and lon) and just with that she would be able to generate a line of path. So, create the points of one in a kilometer.

**Comment by Asratum** [comment]
Glad you're making progress. I think you are looking for something else than KP Find - so far the plugin only provides information from clicks along the line, or from a point layer - it can tell you how far along the line you are when you click, but it does not generate new points along the line.
If you don't care about geodetic distances, you can use the Points along lines function from the Toolbox in QGIS. I don't know of a plugin that can generate points at geodetic distances. I have a plan to add this functionality to KP Find, but it will take one or two months - I will let you know when it is there.

**Comment by Asratum** [comment]
Plugin can now generate point at geodetic distances with version 3.1.0
