### ISSUE TITLE
lat/lon attribute to point layer measurements not correct when project CRS =! RPL CRS

### ISSUE THREAD

**Issue by wienein** [Asratum/KP_find#15]
The lat/lon attributes introduced in version 3.0.3 are only correctly calculated correctly when the project CRS is identical to the RPL CRS

When using EPSG:4326 as Project CRS and the RPL in UTM, the resulting lat/lon look like the formatter was being fed an easting/northing in m

**Comment by Asratum** [comment]
This was fixed in 3.0.4, now the user gets a proper error message.
